version: "3"

services:
  php-apache:
    build:
      context: .
    container_name: modsecurity_php_apache
    depends_on:
      - mysql 
    volumes:
      - ./www:/var/www/html
    ports:
      - 8099:80
  mysql:
    image: mysql:5.6
    container_name: modsecurity_mysql
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sltyyds12345
      MYSQL_DATABASE: users
